/**
 * Canonical vehicle (fleet) tiers — single source of truth.
 *
 * Rules (docs/project/Rules.md §3, docs/project/Architecture.md §6.1):
 * - The canonical vehicle tiers are exactly the five keys below, in this order.
 * - Legacy `innova` and `tempo` may be READ only during compatibility
 *   migration. They are normalized once at the Backend boundary and are never
 *   written to new records or emitted in new public releases.
 * - Unknown enum keys fail with a named validation error.
 *
 * This file is the canonical source. Mirrored copies in
 * backend/src/contracts/, admin/src/contracts/, and react/src/contracts/ are
 * generated by the contract sync process (`npm run contracts:sync`) and must
 * not be hand-edited.
 */

export const CANONICAL_VEHICLE_TIERS = [
  "sedan",
  "ertiga",
  "innova-crysta",
  "tempo-traveller",
  "urbania",
] as const;

export type VehicleTier = (typeof CANONICAL_VEHICLE_TIERS)[number];

/**
 * Legacy keys accepted only on the read path (old records). Never write these
 * keys to new records; never emit them in new public releases.
 */
export const LEGACY_VEHICLE_TIER_MAP: Readonly<Record<string, VehicleTier>> = {
  innova: "innova-crysta",
  tempo: "tempo-traveller",
};

/** Named validation error for unknown fleet keys (Rules.md §3). */
export class UnknownVehicleTierError extends Error {
  readonly code = "VALIDATION_ERROR";
  readonly field = "fleet";

  constructor(key: string) {
    super(
      `Unknown vehicle tier "${key}". Expected one of: ${CANONICAL_VEHICLE_TIERS.join(", ")}.`,
    );
    this.name = "UnknownVehicleTierError";
  }
}

export function isCanonicalVehicleTier(key: string): key is VehicleTier {
  return (CANONICAL_VEHICLE_TIERS as readonly string[]).includes(key);
}

export function isLegacyVehicleTier(
  key: string,
): key is keyof typeof LEGACY_VEHICLE_TIER_MAP {
  return Object.prototype.hasOwnProperty.call(LEGACY_VEHICLE_TIER_MAP, key);
}

/**
 * Normalize a fleet key to its canonical tier.
 *
 * Accepts canonical keys and legacy read-only keys; throws a named
 * UnknownVehicleTierError for anything else. Use this once at the Backend
 * boundary when reading old records. New writes must already use canonical
 * keys — never call this to justify emitting a legacy key.
 */
export function normalizeVehicleTier(key: string): VehicleTier {
  if (isCanonicalVehicleTier(key)) {
    return key;
  }
  if (isLegacyVehicleTier(key)) {
    return LEGACY_VEHICLE_TIER_MAP[key];
  }
  throw new UnknownVehicleTierError(key);
}

/**
 * Assert that every key of a fleet-price record is a canonical tier.
 * Legacy keys are rejected here on purpose: normalization happens once, at the
 * read boundary, and legacy keys must never appear in new records or public
 * releases (docs/CATALOG_PUBLISHING_RECOVERY_PLAN.md §5.1).
 */
export function assertCanonicalFleetPrices(
  fleetPrices: Record<string, number>,
): void {
  for (const key of Object.keys(fleetPrices)) {
    if (!isCanonicalVehicleTier(key)) {
      throw new UnknownVehicleTierError(key);
    }
  }
}
